### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit-documentation-french#2]
At the moment, @poum is the only configured collaborator for this project. Which means that only he reviews pull requests and merges them (I do not speak French and therefore do not touch the translation).

@poum Do you have collaborators that should be added to this project so that they, too, can review and merge pull requests?

**Comment by gbprod** [comment]
Hi ! I've participated to the French translation of the previous repository, I will try to continue as much as possible to stay involved in this translation. If you need more maintainers, I can participate. (I'm French btw ;) )

**Comment by dzc34** [comment]
I can participate to fix some french errors.

**Comment by ecourtial** [comment]
Hi everybody. I can help :)

**Comment by sebastianbergmann** [comment]
The PHPUnit project does not have the resources to coordinate the translation of the PHPUnit documentation into other languages. Some, if not most, of the existing translations have not been up-to-date with the English documentation for quite a while. I have therefore decided to no longer officially support documentation languages other than English. I apologize for any inconvenience this may cause.

I would like to use this opportunity to thank everybody who contributed to this translation effort over the years. Please feel free to continue your translation effort in a fork of this repository.

This repository is about to be archived and the translation of PHPUnit's documentation that was developed in this repository should no longer be considered official.
