### ISSUE TITLE
Branches master et 7.x : comment ça marche ?

### ISSUE THREAD

**Issue by dzc34** [sebastianbergmann/phpunit-documentation-french#29]
@gbprod, comment faut-il faire avec les branches 7.x et master ? 
Chaque commit dans master doit être dupliqué manuellement dans la branche 7.1 ou c'est automatique ?

**Comment by gbprod** [comment]
C'est plus ou moins expliqué ici https://github.com/sebastianbergmann/phpunit-documentation-french/blob/master/CONTRIBUTING.md
Pour faire simple, on fait une branche à chaque nouvelle version ; si une modification concerne la version courante, on PR sur master ; si elle concerne une version particulière (et pas la version actuelle), on PR sur la branche de la version.
Il y a eu quelques petites discussions ici https://github.com/sebastianbergmann/phpunit-documentation-english/issues/11
