### ISSUE TITLE
vérification à faire sur un commit

### ISSUE THREAD

**Issue by dzc34** [sebastianbergmann/phpunit-documentation-french#70]
### commits avant le **5 juin** à traiter
- [x] branche **7.1** --> 7.2, 7.3 and 7.4
  - [x] [b7615d26 - Simplify meaning of constraint in their table ](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/b7615d2674f4fad4372280f588c2865278bf77af) 
 ----> à priori "typo en anglais" / rien à faire   ----> à vérifier

fichier en français : 
https://github.com/sebastianbergmann/phpunit-documentation-french/blob/master/src/assertions.rst#assertthat

**Comment by gbprod** [comment]
Rien à faire IMO

**Comment by dzc34** [comment]
merci @gbprod
