### ISSUE TITLE
Synchro à faire : commits du 14 novembre 2018 au 29 décembre 2018

### ISSUE THREAD

**Issue by dzc34** [sebastianbergmann/phpunit-documentation-french#71]
Si possible traiter les commits les plus anciens ( = commencer par le bas du message), 
en particulier ceux marqués "**help wanted**" qui sont bloquant.

Quasiment tous les commits (sauf mention contraire) doivent être fait dans la branche 7.0 et mergé ensuite dans les branches 7.1, 7.2, 7.3, 7.4, 7.5 et master.

### commits du **14 novembre**   au **29 décembre** 2018

- branche **master**
  - [ ] [2c397 - Leftover from ae01f24](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/2c397d3d7b9d99ad48fee2d5c1641e1cc4921c7b) 
  - [ ] [ae01f2 - Remove DbUnit chapter](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/ae01f2427424087f8217ff19504636c9b03c6280) 

---- 

- branche **7.5** -->  master
  - [ ] [dcd3e4 -  * Remove documentation for deprecated assertInternalType() and assert...](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/dcd3e40cfc629a31581de82298f7a831d61fff3a) 

---- 

- branche **7.4** -->  7.5 et master
  - [ ] [3763a7 - Initial work on documenting --dump-xdebug-filter (and --prepend)](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/3763a75cad3530407030f08a679b8811330a9a46) 
  - [ ] [e868d - Update --help output](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/e868dd201dbb83bc3581000d9db401b2749fe99d) 

---- 

- branche **7.0** --> 7.1, 7.2, 7.3, 7.4, 7.5 et master
  - [ ] [8f6456 - Fix typo in database.rst](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/8f6456a227922e0d74532a8142219cc8bbe6effd) 
  - [ ] [9da996 - Adapted description to use of TestCaseTrait](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/9da9962078abb467f986c477ec20d573723946c7) 
----
synchro précédente  #63 

----

template:
`- [ ] []()`

**Comment by sebastianbergmann** [comment]
The PHPUnit project does not have the resources to coordinate the translation of the PHPUnit documentation into other languages. Some, if not most, of the existing translations have not been up-to-date with the English documentation for quite a while. I have therefore decided to no longer officially support documentation languages other than English. I apologize for any inconvenience this may cause.

I would like to use this opportunity to thank everybody who contributed to this translation effort over the years. Please feel free to continue your translation effort in a fork of this repository.

This repository is about to be archived and the translation of PHPUnit's documentation that was developed in this repository should no longer be considered official.
